stages:
  - buildServer
  - publish
  - publishExternal

workflow:
  rules:
    - if: $CI_COMMIT_TAG

default:
  tags:
    - docker_image
  image: dckregistry.exacaster.com:5000/docker/exagit-runner-artifactory:latest

variables:
    ECR: 'true'
    CDP_TRIGGER: 'false'

include:
  - 'http://exagit.exacaster.com/exacaster/ci-commons/raw/master/.scarabs-template.yml'

buildServer:
  stage: buildServer
  image: 'dckregistry.exacaster.com:5000/docker/java/16-jre-alpine:master'
  script: |
    export TAG=${CI_COMMIT_TAG}
    export SERVER_IMAGE="${CI_REGISTRY_IMAGE}-server"
    cd server/
    ./gradlew dockerBuild -PIMAGE=${SERVER_IMAGE} -PTAG=${TAG}
    ./gradlew dockerPush -PIMAGE=${SERVER_IMAGE} -PTAG=${TAG}


publishInternal:
  interruptible: true
  stage: publish
  script: |
    export TAG=${CI_COMMIT_TAG}
    export SERVER_IMAGE="${CI_REGISTRY_IMAGE}-server"
    docker build . -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} --network host
    docker push $CI_REGISTRY_IMAGE:${TAG}
    docker rmi $CI_REGISTRY_IMAGE:${TAG}
