stages:
  - build
  - quality
  - publish-image-cdp-ecrs
  - release-tag

default:
  tags:
    - docker_image
  image: 'dckregistry.exacaster.com:5000/docker/java/11-jre-slim:master'

include:
  - 'https://exagit.exacaster.com/exacaster/ci-commons/raw/master/.cdp-java-gradle.yml'
  - 'https://exagit.exacaster.com/exacaster/ci-commons/raw/master/cdp/.publish-image-cdp-ecrs.yml'
  - 'https://exagit.exacaster.com/exacaster/ci-commons/raw/master/.cdp-release-tag.yml'

variables:
  TAG: 0.0.$CI_PIPELINE_IID

build:
  stage: build
  rules:
    - if: $NO_BUILD
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      variables:
        TAG: 0.0.$CI_PIPELINE_IID.$CI_COMMIT_REF_SLUG
    - when: always
      allow_failure: false
  before_script:
    - cd server/
  script: |
    ./gradlew build

sonar-merge-request:
  before_script:
    - cd server/

sonar-master:
  before_script:
    - cd server/
