stages:
  - buildServer
  - publish-image-cdp-ecrs

workflow:
  rules:
    - if: $CI_COMMIT_TAG

default:
  tags:
    - docker_image
  image: dckregistry.exacaster.com:5000/docker/exagit-runner-artifactory:latest

include:
  - https://exagit.exacaster.com/exacaster/ci-commons/raw/master/cdp/.publish-image-cdp-ecrs.yml

buildServer:
  stage: buildServer
  image: dckregistry.exacaster.com:5000/docker/java/11-jre-slim:master
  script: |
    cd server/
    ./gradlew build

publish-image-cdp-ecrs:
  variables:
    TAG: $CI_COMMIT_TAG
  rules:
    - if: $NO_BUILD
      when: never
    - if: $ECR_ADDRESS_customer360 && $ECR_ADDRESS_millicom_cdp && $ECR_ADDRESS_stagecat
