lighter:
    kubernetes:
        enabled: true
        namespace: default
        max-log-size: 500
micronaut:
    server:
        cors:
            enabled: true
    application:
        name: lighter
    router:
        static-resources:
            default:
                paths: file:${FRONTEND_PATH:../frontend/build}
                mapping: /lighter/**
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**

    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
