lighter:
    max-running-jobs: 5
    frontend-path: file:${FRONTEND_PATH:../frontend/build}
    kubernetes:
        enabled: true
        master: k8s://kubernetes.default.svc.cluster.local:443
        namespace: spark
        max-log-size: 500
    storage:
        jdbc:
            enabled: true
            url: jdbc:h2:mem:lighter;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
            username: sa
            password: ""
            driverClassName: org.h2.Driver

# Micronaut specific configs
jackson:
    serialization:
        writeDatesAsTimestamps: false

flyway:
    datasources:
        default:
            enabled: true

micronaut:
    server:
        cors:
            enabled: true
    application:
        name: lighter
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**

    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
