micronaut:
    application:
        name: lighter
    router:
        static-resources:
            default:
                paths: file:frontend/build
                mapping: /**
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**

    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
