name: build backend and frontend
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  build-frontend:
    uses: ${{ github.repository }}/.github/workflows/build-frontend.yml@master
  build-java:
    uses: ${{ github.repository }}/.github/workflows/build-java.yml@master
