name: publish docker image
on:
  release:
    types:
      - released

jobs:
  build-frontend:
    uses: ${{ github.repository }}/.github/workflows/build-frontend.yml@master
  build-java:
    uses: ${{ github.repository }}/.github/workflows/build-java.yml@master
  publish-registry:
    uses: ${{ github.repository }}/.github/workflows/publish-registry.yml@master
    needs: [build-frontend, build-java]
